name: tfl_weather
version: '1.0.0'
config-version: 2

profile: tfl_weather

model-paths: ["models"]
test-paths: ["tests"]

models:
  tfl_weather:
    staging:
      materialized: view
    intermediate:
      materialized: table
    marts:
      materialized: table